### who am i
GET http://localhost:3000/admin/WhoAmI HTTP/1.1

### drop table
GET http://localhost:3000/admin/dropTable HTTP/1.1

### create table
GET http://localhost:3000/admin/createTable HTTP/1.1

### /login_page/log_out
GET http://localhost:3000/login_page/log_out HTTP/1.1

### login_page/log_in -- false
POST  http://localhost:3000/login_page/log_in HTTP/1.1
Content-Type: multipart/form-data; boundary=bababa

--bababa
Content-Disposition: form-data; name="password"

lockheed_mg
--bababa
Content-Disposition: form-data; name="name"

lockheed_wrong
--bababa--

### login_page/log_in -- correct
POST  http://localhost:3000/login_page/log_in HTTP/1.1/
Content-Type: multipart/form-data; boundary=bababa

--bababa
Content-Disposition: form-data; name="password"

lockheed_cs
--bababa
Content-Disposition: form-data; name="name"

lockheed_cs
--bababa--



### /stock_page/update_stock -- no item_id
POST  http://localhost:3000/stock_page/update_stock HTTP/1.1/
Content-Type: multipart/form-data; boundary=bababa

--bababa
Content-Disposition: form-data; name="item_id"

8
--bababa
Content-Disposition: form-data; name="name"


--bababa
Content-Disposition: form-data; name="icon"; filename="bbb.png"
Content-Type: image/png


--bababa
Content-Disposition: form-data; name="stock"

12
--bababa
Content-Disposition: form-data; name="price"

2
--bababa--






### login_page/sign up
POST http://localhost:3000/login_page/sign_up HTTP/1.1
Content-Type: multipart/form-data; boundary=flasfls

--flasfls
Content-Disposition: form-data; name="companyName"

lockheed
--flasfls
Content-Disposition: form-data; name="managerName"

lockheed_mg
--flasfls
Content-Disposition: form-data; name="managerPassword"

lockheed_mg
--flasfls
Content-Disposition: form-data; name="cashierName"

lockheed_cs
--flasfls
Content-Disposition: form-data; name="cashierPassword"

lockheed_cs
--flasfls--
#end

###testing
POST http://localhost:3000/testing HTTP/1.1
Content-Type: multipart/form-data; boundary=blablabla

--blablabla
Content-Disposition: form-data; name="hhh"


--blablabla
Content-Disposition: form-data; name="aaa"

12
--blablabla--

# POST http://localhost:3000/testing HTTP/1.1
# Content-Type: multipart/form-data; boundary=----hhhh

# ------hhhh
# Content-Disposition: form-data; name="ggg"

# hhh
# ------hhhh
# Content-Disposition: form-data; name="myfile"; filename="mypng.png"
# Content-Type: image/png

# < ./sampleImg.png
# ------hhhh--


