POST http://localhost:3000/login_page/sign_up HTTP/1.1
Content-Type: multipart/form-data; boundary=flasfls

--flasfls
Content-Disposition: form-data; name="companyName"

lockheed
--flasfls
Content-Disposition: form-data; name="managerName"

LH_mg
--flasfls
Content-Disposition: form-data; name="managerPassword"

password1
--flasfls
Content-Disposition: form-data; name="cashierName"

LH_csh
--flasfls
Content-Disposition: form-data; name="cashierPassword"

password2
--flasfls--




# POST http://localhost:3000/testing HTTP/1.1
# Content-Type: multipart/form-data; boundary=----hhhh

# ------hhhh
# Content-Disposition: form-data; name="ggg"

# hhh
# ------hhhh
# Content-Disposition: form-data; name="myfile"; filename="mypng.png"
# Content-Type: image/png

# < ./sampleImg.png
# ------hhhh--


